### ISSUE TITLE
[DOCS] How do you actually install and try this?

### ISSUE THREAD

**Issue by tazaki** [salt-extensions/saltext-vault#37]
**Description**
I can't seem to find how to actually install and use this extension. My understanding is https://github.com/salt-extensions/saltext-vault/blob/main/README.md is just to install for development. 

The install doc here https://github.com/salt-extensions/saltext-vault/blob/main/docs/topics/installation.md says to just `salt-pip install saltext-vault` but that does not exist.

What am I missing? How do I actually get this installed and try it?

**Suggested Fix**
Better docs or a link to how to install extensions?

**Type of documentation**
Guide

**Additional context**
I am running on a fresh install of salt 3006.5 on almalinux 9.3

Eager to help test but need some guidance please!

**Comment by lkubb** [comment]
Thanks for your interest in this extension! You're correct, this has not been released to PyPi yet. The reason is that imo having a working link to the rendered docs embedded in the release is quite important for this extension, but there is no organization-wide infrastructure for hosting them yet. @nicholasmhughes Has there been any progress regarding hosting the docs for extensions inside the org? Anything I can help with?

For the time being, you would have to build a release yourself to install it:

```
git clone https://github.com/salt-extensions/saltext-vault
cd saltext-vault
# optionally create a venv
python -m pip install build
python -m build --outdir dist/
```

This will yield a built wheel at `dist/saltext.vault-0.1.dev<...>-py2.py3-none-any.whl`, which you should be able to install on your nodes via `salt-pip`.

**Comment by tazaki** [comment]
Thank you! I thought my pip wasn't setup correctly...

I'll give this a try and report back...

**Comment by tazaki** [comment]
Thanks! Was able to get it to build and install with your instructions.
```
[vagrant@saltmaster ~]$ sudo salt-pip list | grep vault
saltext.vault      0.1.dev986+g91e2d10
```

It seems like my vault.read_secrets are still working as expected...and I haven't made any changes. Is there a way to know I am using this ext instead of the default vault modules?

**Comment by lkubb** [comment]
You're welcome. :)

The configuration is backwards-compatible, so it should have still been using the updated modules while warning about the need for updated config (the log message is in fact proof that you were using the modules from this extension). It's still important to update the config though to avoid unnecessary overhead.

Vs the 3006.* `vault` modules, there are many differences, most of which are marked by `.. version(added|changed):: 1.0.0` in the code. An easy check would be to run `salt-call vault.list_secrets some/path keys_only=true`, which should only work with this extension.

**Comment by nicholasmhughes** [comment]
> Has there been any progress regarding hosting the docs for extensions inside the org?

Not yet. It's still on my list, and should get some attention soon.
