### ISSUE TITLE
[FEATURE REQUEST] Add vault_pki modules

### ISSUE THREAD

**Issue by voyvodov** [salt-extensions/saltext-vault#56]
Vault can do a lot more than just storing secrets in KV.
One of the main features is the PKI secret store, which can sign, issue certificates, roatate CAs, or build a whole PKI infrastructure.

**Describe the solution you'd like**
Execution and state modules `vault_pki` (at least) that can control issuers, roles, and certificates.

**Additional context**
I'm preparing some draft based on our custom modules, which were using Salt's built-in vault integration. Will add a link to it once PR is created.

**Comment by lkubb** [comment]
For reference, I wrote a half-baked implementation together with this core, but never got around to using it properly:

https://github.com/lkubb/salt-vault-formula/blob/master/_modules/vault_pki.py
https://github.com/lkubb/salt-vault-formula/blob/master/_states/vault_pki.py

An annoying limitation is the necessity to replicate what the `x509.certificate_managed` state does. It would be lovely to be able to specify a different backend there (other than the `x509` execution module) like I have done in my SSH certificate spin on the x509 modules:

https://github.com/lkubb/salt-openssh-formula/blob/ecd8af39d349fd0b1c412f07328ddb4a81b03737/_states/ssh_pki.py#L180-L246

... which works rather well together with Vault (although the compatibility layer is a bit awkward):

https://github.com/lkubb/salt-vault-formula/blob/430186b529caae1c10e03e1a6ae48b2e884970f6/_modules/vault_ssh.py#L901-L1088

I really want to submit a PR to amend that behavior for the `x509_v2` state module at some point. Afair writing the `vault_pki` modules actually caused me to rewrite the `x509` modules with `x509_v2` in the first place, but since the 3006 release was around the corner, I didn't want to delay their development/review process further with the `backend` behavior.

**Comment by voyvodov** [comment]
In fact we have it (managed certificate from Vault) in our custom state module. Working on it right now to make it work with the extension.

Will open one draft with what I have right now open for comments, so that I can rework what is needed.
