### ISSUE TITLE
[BUG] vault extention fails if client config key is not set

### ISSUE THREAD

**Issue by Syoc** [salt-extensions/saltext-vault#80]
**Description**
Using the Vault extension fails with `VaultException: Requested configuration value client does not exist.` if the client key is not used in the configuration file.

**Setup**
Running extension version 1.1.0 and salt version 3006.8.

**Steps to Reproduce the behavior**
Have a configuration file without the `client:` key and run `salt-call vault.query GET "auth/token/lookup-self"` for example.
Fails with exception mentioned above.
Try again but with the following keys merged into existing config and it should work.
```yaml
vault:
  client:
    max_retries: 5
```

**Expected behavior**
Works without explicitly setting default values.

**Comment by lkubb** [comment]
Huh, this is a message from the master (the runner module). Did you restart your master daemon after upgrading the extension? If you did not, that would explain the absence of the key since the config is loaded once and then cached in the context. This should always be done after an upgrade since the loaded modules might be out of sync.

I specifically made sure that this would not happen with cached config on the minions though.

The fact that one needs to restart daemons after upgrading should be documented though, I don't think it is currently.

**Comment by Syoc** [comment]
You are of course correct. The extension was updated without restarting the salt-master.
I am unable to reproduce the error message after a restart.
